package br.com.vainaweb.projetofinal.enums;

public enum Curso {
    DESENVOLVIMENTO_BACKEND_TURMA_JAVA,
    DESENVOLVIMENTO_BACKEND_TURMA_C_SHARP,
    DESENVOLVIMENTO_FRONTEND_TURMA_REACT,
    DESENVOLVIMENTO_FRONTEND_TURMA_ANGULAR,
    DESENVOLVEDOR_MACHINE_LEARNING_TURMA_PYTHON;
}
